name: leaflow自动签到

on:
  schedule:
    - cron: '0 2 * * *' # 每天UTC时间02:00运行（北京时间10:00）
  workflow_dispatch:  # 允许手动触发

jobs:
  leaflow_check_in:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout private repo
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/leaflow_check_in
          token: ${{ secrets.PRIVATE_REPO_TOKEN }}
          path: scripts

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Playwright and dependencies
        working-directory: scripts
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install --with-deps chromium # 安装 Chromium 浏览器及其运行所需的所有依赖

      - name: Run renew script
        working-directory: scripts
        env:
          LEAFLOW_ACCOUNTS: ${{ secrets.LEAFLOW_ACCOUNTS }}
          WEIRDHOST_EMAIL: ${{ secrets.WEIRDHOST_EMAIL }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python app.py

      - name: Upload Error Screenshot and cookie.json
        uses: actions/upload-artifact@v4
        if: always() # 总是运行，确保无论前一步成功或失败，都能检查是否有截图需要上传
        with:
          name: error-screenshot and cookie.json
          path: |
            *.png
            *.json
          retention-days: 1
